# Generated by Django 5.1.4 on 2026-02-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoiceitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
